name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  HOME: '/home/runner/.config'

jobs:
  bidder-token-gen-time:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install Additional packages - emulator
     run: sdkmanager emulator

    - name: Install additional packages - platform-tools
     run: sdkmanager platform-tools

    - name: Install libpulse
     run: sudo apt -y install libpulse-dev

    - run: sudo apt-get update
    - run: sudo apt install qemu-kvm

    - name: Install kvm
     run: sudo apt install virt-manager

    - run: egrep -c '(vmx|svm)' /proc/cpuinfo
    - run: kvm-ok 
    - name: Enable KVM group perms
      run: |
         echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

    - name: Add user to kvm and change ownership
      run: |
        sudo adduser $USER kvm
        sudo chown $USER /dev/kvm 
    - name: Install System Image
      run: sdkmanager --install 'system-images;android-30;google_apis_playstore;x86_64'

    - name: Create emulator
      run: echo "no" |
        avdmanager create avd -n TestAVD -k "system-images;android-30;google_apis_playstore;x86_64"

    - name: Launch Emulator
      #run: $ANDROID_HOME/emulator/emulator -avd TestAVD -no-audio &
      run: |       
        echo "Starting emulator and waiting for boot to complete...."
        $ANDROID_HOME/emulator/emulator -avd TestAVD -no-skin -no-audio -no-window &
        echo "Emulator has finished booting"
        adb devices

    - name: Install App
      run: ./gradlew installDebug  

    - name: Launch App
      run: adb shell am start -n com.example.test_heap_size/MainActivity    
